USE pollisimo;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE produccion_insumos;
TRUNCATE TABLE producciones;
TRUNCATE TABLE ventas;
TRUNCATE TABLE compras;
TRUNCATE TABLE insumos;
TRUNCATE TABLE productos;
SET FOREIGN_KEY_CHECKS = 1;
INSERT INTO productos (id, nombre, unidad, precio_venta_por_kg, costo_estimado_por_kg) VALUES ('prod-1', 'Milanesa de pollo', 'kg', 9500.0, 4200.0);
INSERT INTO insumos (id, nombre, unidad, stock_inicial, stock_minimo, costo_unitario) VALUES ('ins-1', 'Pechuga de pollo', 'kg', 15.0, 0.0, 15.0);
INSERT INTO insumos (id, nombre, unidad, stock_inicial, stock_minimo, costo_unitario) VALUES ('ins-2', 'Pan rallado', 'kg', 25.0, 0.0, 10.0);
INSERT INTO insumos (id, nombre, unidad, stock_inicial, stock_minimo, costo_unitario) VALUES ('ins-3', 'Huevo', 'unidad', 12.0, 0.0, 22.0);
INSERT INTO insumos (id, nombre, unidad, stock_inicial, stock_minimo, costo_unitario) VALUES ('ins-4', 'Sal', 'Gr', 300.0, 0.0, 165.0);
INSERT INTO insumos (id, nombre, unidad, stock_inicial, stock_minimo, costo_unitario) VALUES ('ins-5', 'Provenzal', 'Gr', 600.0, 0.0, 125.0);
INSERT INTO insumos (id, nombre, unidad, stock_inicial, stock_minimo, costo_unitario) VALUES ('ins-6', 'Pimenton', 'Gr', 840.0, 0.0, 300.0);
INSERT INTO insumos (id, nombre, unidad, stock_inicial, stock_minimo, costo_unitario) VALUES ('ins-7', 'Bandejas', 'Unidad', 100.0, 0.0, 24.0);
INSERT INTO insumos (id, nombre, unidad, stock_inicial, stock_minimo, costo_unitario) VALUES ('ins-8', 'Arranque', 'Unidad', 300.0, 0.0, 24.0);
INSERT INTO insumos (id, nombre, unidad, stock_inicial, stock_minimo, costo_unitario) VALUES ('ins-9', 'Folex', 'unidad', 810.0, 0.0, 120.0);
INSERT INTO insumos (id, nombre, unidad, stock_inicial, stock_minimo, costo_unitario) VALUES ('ins-10', 'Cofias', 'unidad', 4.0, 0.0, 1.0);
INSERT INTO insumos (id, nombre, unidad, stock_inicial, stock_minimo, costo_unitario) VALUES ('ins-11', 'Guantes', 'unidad', 190.0, 0.0, 2.0);
INSERT INTO insumos (id, nombre, unidad, stock_inicial, stock_minimo, costo_unitario) VALUES ('ins-12', 'Camiseta', 'unidad', 0.0, 0.0, 24.0);
INSERT INTO compras (id, fecha, insumo_id, cantidad, costo_unitario, proveedor, notas, afecta_stock) VALUES ('cmp-1', '2026-07-11', 'ins-1', 30.0, 7900.0, 'Fran Mena', 'Ya contemplada en el Stock Inicial', 0);
INSERT INTO compras (id, fecha, insumo_id, cantidad, costo_unitario, proveedor, notas, afecta_stock) VALUES ('cmp-2', '2026-07-11', 'ins-2', 25.0, 1512.0, 'Fran Mena', '', 0);
INSERT INTO compras (id, fecha, insumo_id, cantidad, costo_unitario, proveedor, notas, afecta_stock) VALUES ('cmp-3', '2026-07-11', 'ins-2', 20.0, 1512.0, 'Los Abuelitos', '', 0);
INSERT INTO compras (id, fecha, insumo_id, cantidad, costo_unitario, proveedor, notas, afecta_stock) VALUES ('cmp-4', '2026-07-11', 'ins-3', 60.0, 192.0, 'Karina', '', 0);
INSERT INTO compras (id, fecha, insumo_id, cantidad, costo_unitario, proveedor, notas, afecta_stock) VALUES ('cmp-5', '2026-07-11', 'ins-5', 1000.0, 7.5, 'Karina', '', 0);
INSERT INTO compras (id, fecha, insumo_id, cantidad, costo_unitario, proveedor, notas, afecta_stock) VALUES ('cmp-6', '2026-07-11', 'ins-6', 1000.0, 7.8, 'Karina', '', 0);
INSERT INTO compras (id, fecha, insumo_id, cantidad, costo_unitario, proveedor, notas, afecta_stock) VALUES ('cmp-7', '2026-07-11', 'ins-4', 500.0, 2.4, 'Nini', '', 0);
INSERT INTO compras (id, fecha, insumo_id, cantidad, costo_unitario, proveedor, notas, afecta_stock) VALUES ('cmp-8', '2026-07-11', 'ins-7', 73.0, 79.0, 'QSY', '', 0);
INSERT INTO compras (id, fecha, insumo_id, cantidad, costo_unitario, proveedor, notas, afecta_stock) VALUES ('cmp-9', '2026-07-11', 'ins-7', 27.0, 86.0, 'QSY', '', 0);
INSERT INTO compras (id, fecha, insumo_id, cantidad, costo_unitario, proveedor, notas, afecta_stock) VALUES ('cmp-10', '2026-07-11', 'ins-7', 100.0, 35.58, 'Navarro', '', 0);
INSERT INTO compras (id, fecha, insumo_id, cantidad, costo_unitario, proveedor, notas, afecta_stock) VALUES ('cmp-11', '2026-07-11', 'ins-9', 900.0, 12.0, 'QSY', '', 0);
INSERT INTO compras (id, fecha, insumo_id, cantidad, costo_unitario, proveedor, notas, afecta_stock) VALUES ('cmp-12', '2026-07-11', 'ins-11', 100.0, 131.77, 'QSY', '', 0);
INSERT INTO compras (id, fecha, insumo_id, cantidad, costo_unitario, proveedor, notas, afecta_stock) VALUES ('cmp-13', '2026-07-11', 'ins-11', 100.0, 106.31, 'Navarro', '', 0);
INSERT INTO compras (id, fecha, insumo_id, cantidad, costo_unitario, proveedor, notas, afecta_stock) VALUES ('cmp-14', '2026-07-11', 'ins-10', 7.0, 400.0, 'Pelu perfu', '', 0);
INSERT INTO compras (id, fecha, insumo_id, cantidad, costo_unitario, proveedor, notas, afecta_stock) VALUES ('cmp-15', '2026-07-11', 'ins-8', 350.0, 24.0, 'Navarro', '', 0);
INSERT INTO producciones (id, fecha, producto_id, bandejas_obtenidas, kilos_totales, afecta_stock) VALUES ('tanda-1', '2026-07-12', 'prod-1', 25, 27.3, 0);
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-1-ins-1', 'tanda-1', 'ins-1', 15.0, costo_unitario FROM insumos WHERE id='ins-1';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-1-ins-2', 'tanda-1', 'ins-2', 12.0, costo_unitario FROM insumos WHERE id='ins-2';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-1-ins-3', 'tanda-1', 'ins-3', 24.0, costo_unitario FROM insumos WHERE id='ins-3';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-1-ins-4', 'tanda-1', 'ins-4', 100.0, costo_unitario FROM insumos WHERE id='ins-4';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-1-ins-5', 'tanda-1', 'ins-5', 200.0, costo_unitario FROM insumos WHERE id='ins-5';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-1-ins-6', 'tanda-1', 'ins-6', 80.0, costo_unitario FROM insumos WHERE id='ins-6';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-1-ins-7', 'tanda-1', 'ins-7', 25.0, costo_unitario FROM insumos WHERE id='ins-7';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-1-ins-8', 'tanda-1', 'ins-8', 25.0, costo_unitario FROM insumos WHERE id='ins-8';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-1-ins-9', 'tanda-1', 'ins-9', 75.0, costo_unitario FROM insumos WHERE id='ins-9';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-1-ins-10', 'tanda-1', 'ins-10', 2.0, costo_unitario FROM insumos WHERE id='ins-10';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-1-ins-11', 'tanda-1', 'ins-11', 4.0, costo_unitario FROM insumos WHERE id='ins-11';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-1-ins-12', 'tanda-1', 'ins-12', 25.0, costo_unitario FROM insumos WHERE id='ins-12';
INSERT INTO producciones (id, fecha, producto_id, bandejas_obtenidas, kilos_totales, afecta_stock) VALUES ('tanda-2', '2026-07-14', 'prod-1', 22, 25.0, 0);
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-2-ins-1', 'tanda-2', 'ins-1', 15.0, costo_unitario FROM insumos WHERE id='ins-1';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-2-ins-2', 'tanda-2', 'ins-2', 8.0, costo_unitario FROM insumos WHERE id='ins-2';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-2-ins-3', 'tanda-2', 'ins-3', 24.0, costo_unitario FROM insumos WHERE id='ins-3';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-2-ins-4', 'tanda-2', 'ins-4', 100.0, costo_unitario FROM insumos WHERE id='ins-4';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-2-ins-5', 'tanda-2', 'ins-5', 200.0, costo_unitario FROM insumos WHERE id='ins-5';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-2-ins-6', 'tanda-2', 'ins-6', 80.0, costo_unitario FROM insumos WHERE id='ins-6';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-2-ins-7', 'tanda-2', 'ins-7', 22.0, costo_unitario FROM insumos WHERE id='ins-7';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-2-ins-8', 'tanda-2', 'ins-8', 22.0, costo_unitario FROM insumos WHERE id='ins-8';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-2-ins-9', 'tanda-2', 'ins-9', 66.0, costo_unitario FROM insumos WHERE id='ins-9';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-2-ins-10', 'tanda-2', 'ins-10', 1.0, costo_unitario FROM insumos WHERE id='ins-10';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-2-ins-11', 'tanda-2', 'ins-11', 4.0, costo_unitario FROM insumos WHERE id='ins-11';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-2-ins-12', 'tanda-2', 'ins-12', 22.0, costo_unitario FROM insumos WHERE id='ins-12';
INSERT INTO producciones (id, fecha, producto_id, bandejas_obtenidas, kilos_totales, afecta_stock) VALUES ('tanda-3', '2026-07-18', 'prod-1', 24, 0.0, 1);
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-3-ins-1', 'tanda-3', 'ins-1', 15.0, costo_unitario FROM insumos WHERE id='ins-1';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-3-ins-2', 'tanda-3', 'ins-2', 10.0, costo_unitario FROM insumos WHERE id='ins-2';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-3-ins-3', 'tanda-3', 'ins-3', 22.0, costo_unitario FROM insumos WHERE id='ins-3';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-3-ins-4', 'tanda-3', 'ins-4', 165.0, costo_unitario FROM insumos WHERE id='ins-4';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-3-ins-5', 'tanda-3', 'ins-5', 125.0, costo_unitario FROM insumos WHERE id='ins-5';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-3-ins-6', 'tanda-3', 'ins-6', 300.0, costo_unitario FROM insumos WHERE id='ins-6';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-3-ins-7', 'tanda-3', 'ins-7', 24.0, costo_unitario FROM insumos WHERE id='ins-7';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-3-ins-8', 'tanda-3', 'ins-8', 24.0, costo_unitario FROM insumos WHERE id='ins-8';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-3-ins-9', 'tanda-3', 'ins-9', 120.0, costo_unitario FROM insumos WHERE id='ins-9';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-3-ins-10', 'tanda-3', 'ins-10', 1.0, costo_unitario FROM insumos WHERE id='ins-10';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-3-ins-11', 'tanda-3', 'ins-11', 2.0, costo_unitario FROM insumos WHERE id='ins-11';
INSERT INTO produccion_insumos (id, produccion_id, insumo_id, cantidad_usada, costo_unitario_historico) SELECT 'pi-tanda-3-ins-12', 'tanda-3', 'ins-12', 24.0, costo_unitario FROM insumos WHERE id='ins-12';
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-1', '2026-07-14', 'Estefania Arregui', 'prod-1', 2.230, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-2', '2026-07-14', 'Irma', 'prod-1', 2.136, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-3', '2026-07-14', 'Sofi Magallanes', 'prod-1', 1.115, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-4', '2026-07-14', 'Emi Pereyra', 'prod-1', 1.070, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-5', '2026-07-14', 'Agus Chacon', 'prod-1', 1.050, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-6', '2026-07-14', 'Berni', 'prod-1', 1.105, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-7', '2026-07-14', 'Andre', 'prod-1', 1.105, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-8', '2026-07-14', 'Cami Harguyntegui', 'prod-1', 3.117, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-9', '2026-07-14', 'Mari Murue', 'prod-1', 2.030, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-10', '2026-07-14', 'Cata Domato', 'prod-1', 1.084, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-11', '2026-07-14', 'Dasil', 'prod-1', 1.050, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-12', '2026-07-14', 'Ariel Izquierdo', 'prod-1', 1.000, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-13', '2026-07-14', 'Carolina Heger', 'prod-1', 1.000, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-14', '2026-07-15', 'Loli Herrera', 'prod-1', 2.215, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-15', '2026-07-16', 'Lili Loker', 'prod-1', NULL, 9500.0, 'Efectivo', 'Entregado', 'Reservado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-16', '2026-07-16', 'Fran Isnaldi', 'prod-1', 1.084, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-17', '2026-07-16', 'Euge Castelli', 'prod-1', 2.263, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-18', '2026-07-16', 'Zul', 'prod-1', 2.189, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-19', '2026-07-16', 'Claudia Biolay', 'prod-1', NULL, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-20', '2026-07-16', 'Maria Elva Martinez', 'prod-1', 1.230, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-21', '2026-07-18', 'Jose', 'prod-1', 4.431, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-22', '2026-07-18', 'Ana Calligo', 'prod-1', 2.105, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-23', '2026-07-18', 'Mari Murue', 'prod-1', 2.200, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-24', '2026-07-18', 'Georgi', 'prod-1', 1.210, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-25', '2026-07-18', 'Marce Gonzalez', 'prod-1', 2.263, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-26', '2026-07-18', 'Augusto', 'prod-1', 2.168, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-27', '2026-07-18', 'Pedro Albornoz', 'prod-1', 1.315, 9500.0, 'Efectivo', 'Entregado', 'Entregado');
INSERT INTO ventas (id, fecha, cliente, producto_id, peso_kg, precio_por_kg, medio_pago, estado, notas) VALUES ('vta-real-28', '2026-07-18', 'Pedro Albornoz', 'prod-1', 2.294, 9500.0, 'Efectivo', 'Entregado', 'Entregado');